image: docker

variables:
  APP_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}

stages:
  - build

build-app-image:
  stage: build
  image: docker
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build --target=release --pull -t  ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG} .
    - docker push  ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  after_script:
    - docker logout ${CI_REGISTRY}

