apiVersion: v1
kind: Service
metadata:
  name: dr-pump
  labels:
    k8s-app: dr-pump
    app-env: {{ .Values.env }}
spec:
  type: LoadBalancer
  selector:
    k8s-app: dr-pump
    app-env: {{ .Values.env }}
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.targetPort }}
